baseURL = "gjakovaime.github.io"
languageCode = "en-us"
title = "INOX"
theme = "ananke"
publishDir = "docs"
[params]
    background_color_class = "bg-dark-gray"
    logo = "/images/inox-logo-small.png"